apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170498049
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170498049
    app.kubernetes.io/part-of: test-app-170498049
  name: java-quarkus-170498049
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170498049
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170498049
    spec:
      containers:
      - image: quay.io/hacdev/9rbqglkq-tenant/test-app-170498049/java-quarkus-170498049@sha256:8b03b22de29811e8cea30d8b9e48866d1f036becbfc06f2657f7d9e0fbf30dfb
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
