apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170498049
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170498049
    app.kubernetes.io/part-of: test-app-170498049
  name: java-quarkus-170498049
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-170498049
status:
  loadBalancer: {}
